import type { SceneEditorConfig, EditorNpcEntry, EditorZoneEntry } from './sceneEditorTypes'
import type { SavedPlacedObject } from './sandboxSceneSchema'
import type { RoomPackageScene } from './roomPackageTypes'

/**
 * Serialize the current editor state to a TypeScript literal that can be
 * pasted directly into a host page's scene config file.
 *
 * Output mirrors the `SceneEditorConfig` interface so it compiles without
 * modification.
 */
export function serializeEditorConfigTS(
  npcs: EditorNpcEntry[],
  zones: EditorZoneEntry[],
  config: SceneEditorConfig,
): string {
  const lines: string[] = []
  lines.push(`// Generated by @base/ui SceneEditor — ${new Date().toLocaleDateString()}`)
  lines.push(`import type { SceneEditorConfig } from '@base/ui'`)
  lines.push(``)
  lines.push(`export const SCENE_EDITOR_CONFIG: SceneEditorConfig = {`)

  if (config.floorGlbUrl) {
    lines.push(`  floorGlbUrl: ${JSON.stringify(config.floorGlbUrl)},`)
  }
  if (config.contextGlbUrls && config.contextGlbUrls.length > 0) {
    lines.push(`  contextGlbUrls: [`)
    for (const url of config.contextGlbUrls) {
      lines.push(`    ${JSON.stringify(url)},`)
    }
    lines.push(`  ],`)
  }
  if (config.storageKeyPrefix) {
    lines.push(`  storageKeyPrefix: ${JSON.stringify(config.storageKeyPrefix)},`)
  }
  if (config.exportNamePrefix) {
    lines.push(`  exportNamePrefix: ${JSON.stringify(config.exportNamePrefix)},`)
  }

  if (npcs.length > 0) {
    lines.push(`  npcs: [`)
    for (const npc of npcs) {
      lines.push(`    {`)
      lines.push(`      entityId: ${JSON.stringify(npc.entityId)},`)
      if (npc.label && npc.label !== npc.entityId) {
        lines.push(`      label: ${JSON.stringify(npc.label)},`)
      }
      lines.push(`      x: ${fmt(npc.x)}, z: ${fmt(npc.z)},`)
      if (npc.y !== undefined && npc.y !== 0) {
        lines.push(`      y: ${fmt(npc.y)},`)
      }
      if (npc.proximityRadius !== undefined) {
        lines.push(`      proximityRadius: ${npc.proximityRadius},`)
      }
      if (npc.assetId) lines.push(`      assetId: ${JSON.stringify(npc.assetId)},`)
      if (npc.animationPackAssetId) lines.push(`      animationPackAssetId: ${JSON.stringify(npc.animationPackAssetId)},`)
      if (npc.defaultClip) lines.push(`      defaultClip: ${JSON.stringify(npc.defaultClip)},`)
      if (npc.rotationY !== undefined && npc.rotationY !== 0) {
        lines.push(`      rotationY: ${fmt(npc.rotationY)},`)
      }
      if (npc.scale !== undefined && npc.scale !== 1) {
        lines.push(`      scale: ${fmt(npc.scale)},`)
      }
      lines.push(`    },`)
    }
    lines.push(`  ],`)
  } else {
    lines.push(`  npcs: [],`)
  }

  if (zones.length > 0) {
    lines.push(`  zones: [`)
    for (const z of zones) {
      lines.push(`    {`)
      lines.push(`      id: ${JSON.stringify(z.id)},`)
      lines.push(`      type: ${JSON.stringify(z.type)},`)
      if (z.label && z.label !== z.id) {
        lines.push(`      label: ${JSON.stringify(z.label)},`)
      }
      lines.push(`      x: ${fmt(z.x)}, z: ${fmt(z.z)}, radius: ${fmt(z.radius)},`)
      if (z.targetSceneId) lines.push(`      targetSceneId: ${JSON.stringify(z.targetSceneId)},`)
      if (z.color !== undefined) lines.push(`      color: ${z.color},`)
      lines.push(`    },`)
    }
    lines.push(`  ],`)
  } else {
    lines.push(`  zones: [],`)
  }

  if (config.spawnPoint) {
    lines.push(`  spawnPoint: { x: ${fmt(config.spawnPoint.x)}, z: ${fmt(config.spawnPoint.z)} },`)
  }

  lines.push(`}`)
  return lines.join('\n')
}

function fmt(n: number): string {
  return Number.isInteger(n) ? String(n) : n.toFixed(3).replace(/\.?0+$/, '')
}

/**
 * Build a RoomPackageScene from the current editor state snapshot.
 * Pure / synchronous — no DB access.  Asset blobs are collected separately
 * by exportRoomPackage().
 */
export function buildRoomPackageScene(
  placedObjects: SavedPlacedObject[],
  config: SceneEditorConfig,
): RoomPackageScene {
  return {
    placedObjects,
    npcs: config.npcs ?? [],
    zones: config.zones ?? [],
    spawnPoint: config.spawnPoint,
    ambientAudioAssetId: config.ambientAudioAssetId,
    ambientAudioVolume: config.ambientAudioVolume,
  }
}
